Feature/i187 atualizar phpcsfixer
EscolaDeSaudePublica/isus-api pull request #190
Opened 2022-01-13 17:28 UTC by Laysacunha

Responsáveis:  
@Laysacunha 

Linked Issue:  
Close #187 

### Descrição

Atualiza pacote php-cs-fixer para versão 3.4. Atualização foi necessária porque a versão 2.x já estava sem suporte e o comando de rodar o php-cs-fixer já orientava atualização.

### Passos a passo para teste

Acessar arquivo package.json e verificar a versão atualizada.

## Checklist para criação do PR

- [ ] Testes foram implementados (novos ou não)
- [x] Issue foi definida no PR (Linked Issue na coluna à direita da página)
- [x] Pessoas contribuidoras foram definidas no PR (Assigners no PR)

2022-01-20 14:19 UTC, ericsonmoreira requested changes
Dá uma olhada naquele comentário que coloquei sobre o nome da classe. Suspeito que vc mudou sem querer @Laysacunha. 

Fora isso tá ok.

2022-01-20 14:19 UTC, ericsonmoreira commented on database/seeders/EspecidadesSeeder.php
> +class EspecidadesSeeder extends Seeder
Aqui é `EspecidadesSeeder` em vez de `EspecialidadesSeeder`?

2022-01-20 20:44 UTC, Laysacunha commented on database/seeders/EspecidadesSeeder.php
> +class EspecidadesSeeder extends Seeder
Arquivo estava com o nome incorreto e php-cs-fix renomeou a classe de acordo com o nome do arquivo. 
Alteração para o nome correto foi realizada. Branch atualizada.

Arquivos em que as aspas foram alteradas para single foram checados e podem permanecer com aspas simples.

2022-01-26 12:56 UTC, ericsonmoreira approved these changes
GTM

2022-01-26 12:56 UTC, merged